-- ==============================================================
-- Generated by Dot2Vhdl ver. 2.0
-- File created: Thu May  4 16:07:25 2023

-- ==============================================================
library IEEE; 
use IEEE.std_logic_1164.all; 
use IEEE.numeric_std.all; 
use work.customTypes.all; 
-- ==============================================================
entity fir is 
port (
	clk:  in std_logic;
	rst:  in std_logic;
	start_in:  in std_logic_vector (0 downto 0);
	start_valid:  in std_logic;
	start_ready:  out std_logic;
	end_out:  out std_logic_vector (31 downto 0);
	end_valid:  out std_logic;
	end_ready:  in std_logic;
	arg_1_din : in std_logic_vector (31 downto 0);
	arg_1_valid_in : in std_logic;
	arg_1_ready_out : out std_logic;
	A_address0 : out std_logic_vector (31 downto 0);
	A_ce0 : out std_logic;
	A_we0 : out std_logic;
	A_dout0 : out std_logic_vector (31 downto 0);
	A_din0 : in std_logic_vector (31 downto 0);
	A_address1 : out std_logic_vector (31 downto 0);
	A_ce1 : out std_logic;
	A_we1 : out std_logic;
	A_dout1 : out std_logic_vector (31 downto 0);
	A_din1 : in std_logic_vector (31 downto 0));
end;

architecture behavioral of fir is 

	signal arg_1_clk : std_logic;
	signal arg_1_rst : std_logic;
	signal arg_1_dataInArray_0 : std_logic_vector(31 downto 0);
	signal arg_1_pValidArray_0 : std_logic;
	signal arg_1_readyArray_0 : std_logic;
	signal arg_1_nReadyArray_0 : std_logic;
	signal arg_1_validArray_0 : std_logic;
	signal arg_1_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal cst_0_clk : std_logic;
	signal cst_0_rst : std_logic;
	signal cst_0_dataInArray_0 : std_logic_vector(31 downto 0);
	signal cst_0_pValidArray_0 : std_logic;
	signal cst_0_readyArray_0 : std_logic;
	signal cst_0_nReadyArray_0 : std_logic;
	signal cst_0_validArray_0 : std_logic;
	signal cst_0_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal cst_1_clk : std_logic;
	signal cst_1_rst : std_logic;
	signal cst_1_dataInArray_0 : std_logic_vector(31 downto 0);
	signal cst_1_pValidArray_0 : std_logic;
	signal cst_1_readyArray_0 : std_logic;
	signal cst_1_nReadyArray_0 : std_logic;
	signal cst_1_validArray_0 : std_logic;
	signal cst_1_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal start_0_clk : std_logic;
	signal start_0_rst : std_logic;
	signal start_0_dataInArray_0 : std_logic_vector(0 downto 0);
	signal start_0_pValidArray_0 : std_logic;
	signal start_0_readyArray_0 : std_logic;
	signal start_0_nReadyArray_0 : std_logic;
	signal start_0_validArray_0 : std_logic;
	signal start_0_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal forkC_5_clk : std_logic;
	signal forkC_5_rst : std_logic;
	signal forkC_5_dataInArray_0 : std_logic_vector(0 downto 0);
	signal forkC_5_pValidArray_0 : std_logic;
	signal forkC_5_readyArray_0 : std_logic;
	signal forkC_5_nReadyArray_0 : std_logic;
	signal forkC_5_validArray_0 : std_logic;
	signal forkC_5_dataOutArray_0 : std_logic_vector(0 downto 0);
	signal forkC_5_nReadyArray_1 : std_logic;
	signal forkC_5_validArray_1 : std_logic;
	signal forkC_5_dataOutArray_1 : std_logic_vector(0 downto 0);

	signal phi_0_clk : std_logic;
	signal phi_0_rst : std_logic;
	signal phi_0_dataInArray_0 : std_logic_vector(0 downto 0);
	signal phi_0_dataInArray_1 : std_logic_vector(31 downto 0);
	signal phi_0_dataInArray_2 : std_logic_vector(31 downto 0);
	signal phi_0_pValidArray_0 : std_logic;
	signal phi_0_pValidArray_1 : std_logic;
	signal phi_0_pValidArray_2 : std_logic;
	signal phi_0_readyArray_0 : std_logic;
	signal phi_0_readyArray_1 : std_logic;
	signal phi_0_readyArray_2 : std_logic;
	signal phi_0_nReadyArray_0 : std_logic;
	signal phi_0_validArray_0 : std_logic;
	signal phi_0_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal phi_1_clk : std_logic;
	signal phi_1_rst : std_logic;
	signal phi_1_dataInArray_0 : std_logic_vector(0 downto 0);
	signal phi_1_dataInArray_1 : std_logic_vector(31 downto 0);
	signal phi_1_dataInArray_2 : std_logic_vector(31 downto 0);
	signal phi_1_pValidArray_0 : std_logic;
	signal phi_1_pValidArray_1 : std_logic;
	signal phi_1_pValidArray_2 : std_logic;
	signal phi_1_readyArray_0 : std_logic;
	signal phi_1_readyArray_1 : std_logic;
	signal phi_1_readyArray_2 : std_logic;
	signal phi_1_nReadyArray_0 : std_logic;
	signal phi_1_validArray_0 : std_logic;
	signal phi_1_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal phi_2_clk : std_logic;
	signal phi_2_rst : std_logic;
	signal phi_2_dataInArray_0 : std_logic_vector(0 downto 0);
	signal phi_2_dataInArray_1 : std_logic_vector(31 downto 0);
	signal phi_2_dataInArray_2 : std_logic_vector(31 downto 0);
	signal phi_2_pValidArray_0 : std_logic;
	signal phi_2_pValidArray_1 : std_logic;
	signal phi_2_pValidArray_2 : std_logic;
	signal phi_2_readyArray_0 : std_logic;
	signal phi_2_readyArray_1 : std_logic;
	signal phi_2_readyArray_2 : std_logic;
	signal phi_2_nReadyArray_0 : std_logic;
	signal phi_2_validArray_0 : std_logic;
	signal phi_2_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal cst_2_clk : std_logic;
	signal cst_2_rst : std_logic;
	signal cst_2_dataInArray_0 : std_logic_vector(31 downto 0);
	signal cst_2_pValidArray_0 : std_logic;
	signal cst_2_readyArray_0 : std_logic;
	signal cst_2_nReadyArray_0 : std_logic;
	signal cst_2_validArray_0 : std_logic;
	signal cst_2_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal and_4_clk : std_logic;
	signal and_4_rst : std_logic;
	signal and_4_dataInArray_0 : std_logic_vector(31 downto 0);
	signal and_4_dataInArray_1 : std_logic_vector(31 downto 0);
	signal and_4_pValidArray_0 : std_logic;
	signal and_4_pValidArray_1 : std_logic;
	signal and_4_readyArray_0 : std_logic;
	signal and_4_readyArray_1 : std_logic;
	signal and_4_nReadyArray_0 : std_logic;
	signal and_4_validArray_0 : std_logic;
	signal and_4_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal cst_3_clk : std_logic;
	signal cst_3_rst : std_logic;
	signal cst_3_dataInArray_0 : std_logic_vector(31 downto 0);
	signal cst_3_pValidArray_0 : std_logic;
	signal cst_3_readyArray_0 : std_logic;
	signal cst_3_nReadyArray_0 : std_logic;
	signal cst_3_validArray_0 : std_logic;
	signal cst_3_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal icmp_5_clk : std_logic;
	signal icmp_5_rst : std_logic;
	signal icmp_5_dataInArray_0 : std_logic_vector(31 downto 0);
	signal icmp_5_dataInArray_1 : std_logic_vector(31 downto 0);
	signal icmp_5_pValidArray_0 : std_logic;
	signal icmp_5_pValidArray_1 : std_logic;
	signal icmp_5_readyArray_0 : std_logic;
	signal icmp_5_readyArray_1 : std_logic;
	signal icmp_5_nReadyArray_0 : std_logic;
	signal icmp_5_validArray_0 : std_logic;
	signal icmp_5_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal source_0_clk : std_logic;
	signal source_0_rst : std_logic;
	signal source_0_nReadyArray_0 : std_logic;
	signal source_0_validArray_0 : std_logic;
	signal source_0_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal source_1_clk : std_logic;
	signal source_1_rst : std_logic;
	signal source_1_nReadyArray_0 : std_logic;
	signal source_1_validArray_0 : std_logic;
	signal source_1_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal branch_3_clk : std_logic;
	signal branch_3_rst : std_logic;
	signal branch_3_dataInArray_0 : std_logic_vector(31 downto 0);
	signal branch_3_dataInArray_1 : std_logic_vector(0 downto 0);
	signal branch_3_pValidArray_0 : std_logic;
	signal branch_3_pValidArray_1 : std_logic;
	signal branch_3_readyArray_0 : std_logic;
	signal branch_3_readyArray_1 : std_logic;
	signal branch_3_nReadyArray_0 : std_logic;
	signal branch_3_validArray_0 : std_logic;
	signal branch_3_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal branch_3_nReadyArray_1 : std_logic;
	signal branch_3_validArray_1 : std_logic;
	signal branch_3_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal branch_4_clk : std_logic;
	signal branch_4_rst : std_logic;
	signal branch_4_dataInArray_0 : std_logic_vector(31 downto 0);
	signal branch_4_dataInArray_1 : std_logic_vector(0 downto 0);
	signal branch_4_pValidArray_0 : std_logic;
	signal branch_4_pValidArray_1 : std_logic;
	signal branch_4_readyArray_0 : std_logic;
	signal branch_4_readyArray_1 : std_logic;
	signal branch_4_nReadyArray_0 : std_logic;
	signal branch_4_validArray_0 : std_logic;
	signal branch_4_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal branch_4_nReadyArray_1 : std_logic;
	signal branch_4_validArray_1 : std_logic;
	signal branch_4_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal branch_7_clk : std_logic;
	signal branch_7_rst : std_logic;
	signal branch_7_dataInArray_0 : std_logic_vector(31 downto 0);
	signal branch_7_dataInArray_1 : std_logic_vector(0 downto 0);
	signal branch_7_pValidArray_0 : std_logic;
	signal branch_7_pValidArray_1 : std_logic;
	signal branch_7_readyArray_0 : std_logic;
	signal branch_7_readyArray_1 : std_logic;
	signal branch_7_nReadyArray_0 : std_logic;
	signal branch_7_validArray_0 : std_logic;
	signal branch_7_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal branch_7_nReadyArray_1 : std_logic;
	signal branch_7_validArray_1 : std_logic;
	signal branch_7_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal Synch_0_clk : std_logic;
	signal Synch_0_rst : std_logic;
	signal Synch_0_dataInArray_0 : std_logic_vector(31 downto 0);
	signal Synch_0_dataInArray_1 : std_logic_vector(31 downto 0);
	signal Synch_0_dataInArray_2 : std_logic_vector(31 downto 0);
	signal Synch_0_pValidArray_0 : std_logic;
	signal Synch_0_pValidArray_1 : std_logic;
	signal Synch_0_pValidArray_2 : std_logic;
	signal Synch_0_readyArray_0 : std_logic;
	signal Synch_0_readyArray_1 : std_logic;
	signal Synch_0_readyArray_2 : std_logic;
	signal Synch_0_nReadyArray_0 : std_logic;
	signal Synch_0_validArray_0 : std_logic;
	signal Synch_0_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal Synch_0_nReadyArray_1 : std_logic;
	signal Synch_0_validArray_1 : std_logic;
	signal Synch_0_dataOutArray_1 : std_logic_vector(31 downto 0);
	signal Synch_0_nReadyArray_2 : std_logic;
	signal Synch_0_validArray_2 : std_logic;
	signal Synch_0_dataOutArray_2 : std_logic_vector(31 downto 0);

	signal fork_0_clk : std_logic;
	signal fork_0_rst : std_logic;
	signal fork_0_dataInArray_0 : std_logic_vector(31 downto 0);
	signal fork_0_pValidArray_0 : std_logic;
	signal fork_0_readyArray_0 : std_logic;
	signal fork_0_nReadyArray_0 : std_logic;
	signal fork_0_validArray_0 : std_logic;
	signal fork_0_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal fork_0_nReadyArray_1 : std_logic;
	signal fork_0_validArray_1 : std_logic;
	signal fork_0_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal fork_1_clk : std_logic;
	signal fork_1_rst : std_logic;
	signal fork_1_dataInArray_0 : std_logic_vector(31 downto 0);
	signal fork_1_pValidArray_0 : std_logic;
	signal fork_1_readyArray_0 : std_logic;
	signal fork_1_nReadyArray_0 : std_logic;
	signal fork_1_validArray_0 : std_logic;
	signal fork_1_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal fork_1_nReadyArray_1 : std_logic;
	signal fork_1_validArray_1 : std_logic;
	signal fork_1_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal fork_2_clk : std_logic;
	signal fork_2_rst : std_logic;
	signal fork_2_dataInArray_0 : std_logic_vector(31 downto 0);
	signal fork_2_pValidArray_0 : std_logic;
	signal fork_2_readyArray_0 : std_logic;
	signal fork_2_nReadyArray_0 : std_logic;
	signal fork_2_validArray_0 : std_logic;
	signal fork_2_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal fork_2_nReadyArray_1 : std_logic;
	signal fork_2_validArray_1 : std_logic;
	signal fork_2_dataOutArray_1 : std_logic_vector(31 downto 0);
	signal fork_2_nReadyArray_2 : std_logic;
	signal fork_2_validArray_2 : std_logic;
	signal fork_2_dataOutArray_2 : std_logic_vector(31 downto 0);
	signal fork_2_nReadyArray_3 : std_logic;
	signal fork_2_validArray_3 : std_logic;
	signal fork_2_dataOutArray_3 : std_logic_vector(31 downto 0);
	signal fork_2_nReadyArray_4 : std_logic;
	signal fork_2_validArray_4 : std_logic;
	signal fork_2_dataOutArray_4 : std_logic_vector(31 downto 0);

	signal load_9_clk : std_logic;
	signal load_9_rst : std_logic;
	signal load_9_dataInArray_0 : std_logic_vector(31 downto 0);
	signal load_9_dataInArray_1 : std_logic_vector(31 downto 0);
	signal load_9_pValidArray_0 : std_logic;
	signal load_9_pValidArray_1 : std_logic;
	signal load_9_readyArray_0 : std_logic;
	signal load_9_readyArray_1 : std_logic;
	signal load_9_nReadyArray_0 : std_logic;
	signal load_9_validArray_0 : std_logic;
	signal load_9_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal load_9_nReadyArray_1 : std_logic;
	signal load_9_validArray_1 : std_logic;
	signal load_9_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal mul_10_clk : std_logic;
	signal mul_10_rst : std_logic;
	signal mul_10_dataInArray_0 : std_logic_vector(31 downto 0);
	signal mul_10_dataInArray_1 : std_logic_vector(31 downto 0);
	signal mul_10_pValidArray_0 : std_logic;
	signal mul_10_pValidArray_1 : std_logic;
	signal mul_10_readyArray_0 : std_logic;
	signal mul_10_readyArray_1 : std_logic;
	signal mul_10_nReadyArray_0 : std_logic;
	signal mul_10_validArray_0 : std_logic;
	signal mul_10_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal cst_4_clk : std_logic;
	signal cst_4_rst : std_logic;
	signal cst_4_dataInArray_0 : std_logic_vector(31 downto 0);
	signal cst_4_pValidArray_0 : std_logic;
	signal cst_4_readyArray_0 : std_logic;
	signal cst_4_nReadyArray_0 : std_logic;
	signal cst_4_validArray_0 : std_logic;
	signal cst_4_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal add_12_clk : std_logic;
	signal add_12_rst : std_logic;
	signal add_12_dataInArray_0 : std_logic_vector(31 downto 0);
	signal add_12_dataInArray_1 : std_logic_vector(31 downto 0);
	signal add_12_pValidArray_0 : std_logic;
	signal add_12_pValidArray_1 : std_logic;
	signal add_12_readyArray_0 : std_logic;
	signal add_12_readyArray_1 : std_logic;
	signal add_12_nReadyArray_0 : std_logic;
	signal add_12_validArray_0 : std_logic;
	signal add_12_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal load_15_clk : std_logic;
	signal load_15_rst : std_logic;
	signal load_15_dataInArray_0 : std_logic_vector(31 downto 0);
	signal load_15_dataInArray_1 : std_logic_vector(31 downto 0);
	signal load_15_pValidArray_0 : std_logic;
	signal load_15_pValidArray_1 : std_logic;
	signal load_15_readyArray_0 : std_logic;
	signal load_15_readyArray_1 : std_logic;
	signal load_15_nReadyArray_0 : std_logic;
	signal load_15_validArray_0 : std_logic;
	signal load_15_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal load_15_nReadyArray_1 : std_logic;
	signal load_15_validArray_1 : std_logic;
	signal load_15_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal add_16_clk : std_logic;
	signal add_16_rst : std_logic;
	signal add_16_dataInArray_0 : std_logic_vector(31 downto 0);
	signal add_16_dataInArray_1 : std_logic_vector(31 downto 0);
	signal add_16_pValidArray_0 : std_logic;
	signal add_16_pValidArray_1 : std_logic;
	signal add_16_readyArray_0 : std_logic;
	signal add_16_readyArray_1 : std_logic;
	signal add_16_nReadyArray_0 : std_logic;
	signal add_16_validArray_0 : std_logic;
	signal add_16_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal cst_5_clk : std_logic;
	signal cst_5_rst : std_logic;
	signal cst_5_dataInArray_0 : std_logic_vector(31 downto 0);
	signal cst_5_pValidArray_0 : std_logic;
	signal cst_5_readyArray_0 : std_logic;
	signal cst_5_nReadyArray_0 : std_logic;
	signal cst_5_validArray_0 : std_logic;
	signal cst_5_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal add_17_clk : std_logic;
	signal add_17_rst : std_logic;
	signal add_17_dataInArray_0 : std_logic_vector(31 downto 0);
	signal add_17_dataInArray_1 : std_logic_vector(31 downto 0);
	signal add_17_pValidArray_0 : std_logic;
	signal add_17_pValidArray_1 : std_logic;
	signal add_17_readyArray_0 : std_logic;
	signal add_17_readyArray_1 : std_logic;
	signal add_17_nReadyArray_0 : std_logic;
	signal add_17_validArray_0 : std_logic;
	signal add_17_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal source_2_clk : std_logic;
	signal source_2_rst : std_logic;
	signal source_2_nReadyArray_0 : std_logic;
	signal source_2_validArray_0 : std_logic;
	signal source_2_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal source_3_clk : std_logic;
	signal source_3_rst : std_logic;
	signal source_3_nReadyArray_0 : std_logic;
	signal source_3_validArray_0 : std_logic;
	signal source_3_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal phi_19_clk : std_logic;
	signal phi_19_rst : std_logic;
	signal phi_19_dataInArray_0 : std_logic_vector(0 downto 0);
	signal phi_19_dataInArray_1 : std_logic_vector(31 downto 0);
	signal phi_19_dataInArray_2 : std_logic_vector(31 downto 0);
	signal phi_19_pValidArray_0 : std_logic;
	signal phi_19_pValidArray_1 : std_logic;
	signal phi_19_pValidArray_2 : std_logic;
	signal phi_19_readyArray_0 : std_logic;
	signal phi_19_readyArray_1 : std_logic;
	signal phi_19_readyArray_2 : std_logic;
	signal phi_19_nReadyArray_0 : std_logic;
	signal phi_19_validArray_0 : std_logic;
	signal phi_19_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal phi_20_clk : std_logic;
	signal phi_20_rst : std_logic;
	signal phi_20_dataInArray_0 : std_logic_vector(0 downto 0);
	signal phi_20_dataInArray_1 : std_logic_vector(31 downto 0);
	signal phi_20_dataInArray_2 : std_logic_vector(31 downto 0);
	signal phi_20_pValidArray_0 : std_logic;
	signal phi_20_pValidArray_1 : std_logic;
	signal phi_20_pValidArray_2 : std_logic;
	signal phi_20_readyArray_0 : std_logic;
	signal phi_20_readyArray_1 : std_logic;
	signal phi_20_readyArray_2 : std_logic;
	signal phi_20_nReadyArray_0 : std_logic;
	signal phi_20_validArray_0 : std_logic;
	signal phi_20_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal cst_6_clk : std_logic;
	signal cst_6_rst : std_logic;
	signal cst_6_dataInArray_0 : std_logic_vector(31 downto 0);
	signal cst_6_pValidArray_0 : std_logic;
	signal cst_6_readyArray_0 : std_logic;
	signal cst_6_nReadyArray_0 : std_logic;
	signal cst_6_validArray_0 : std_logic;
	signal cst_6_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal add_21_clk : std_logic;
	signal add_21_rst : std_logic;
	signal add_21_dataInArray_0 : std_logic_vector(31 downto 0);
	signal add_21_dataInArray_1 : std_logic_vector(31 downto 0);
	signal add_21_pValidArray_0 : std_logic;
	signal add_21_pValidArray_1 : std_logic;
	signal add_21_readyArray_0 : std_logic;
	signal add_21_readyArray_1 : std_logic;
	signal add_21_nReadyArray_0 : std_logic;
	signal add_21_validArray_0 : std_logic;
	signal add_21_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal cst_7_clk : std_logic;
	signal cst_7_rst : std_logic;
	signal cst_7_dataInArray_0 : std_logic_vector(31 downto 0);
	signal cst_7_pValidArray_0 : std_logic;
	signal cst_7_readyArray_0 : std_logic;
	signal cst_7_nReadyArray_0 : std_logic;
	signal cst_7_validArray_0 : std_logic;
	signal cst_7_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal icmp_22_clk : std_logic;
	signal icmp_22_rst : std_logic;
	signal icmp_22_dataInArray_0 : std_logic_vector(31 downto 0);
	signal icmp_22_dataInArray_1 : std_logic_vector(31 downto 0);
	signal icmp_22_pValidArray_0 : std_logic;
	signal icmp_22_pValidArray_1 : std_logic;
	signal icmp_22_readyArray_0 : std_logic;
	signal icmp_22_readyArray_1 : std_logic;
	signal icmp_22_nReadyArray_0 : std_logic;
	signal icmp_22_validArray_0 : std_logic;
	signal icmp_22_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal source_4_clk : std_logic;
	signal source_4_rst : std_logic;
	signal source_4_nReadyArray_0 : std_logic;
	signal source_4_validArray_0 : std_logic;
	signal source_4_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal source_5_clk : std_logic;
	signal source_5_rst : std_logic;
	signal source_5_nReadyArray_0 : std_logic;
	signal source_5_validArray_0 : std_logic;
	signal source_5_dataOutArray_0 : std_logic_vector(0 downto 0);

	signal branch_0_clk : std_logic;
	signal branch_0_rst : std_logic;
	signal branch_0_dataInArray_0 : std_logic_vector(31 downto 0);
	signal branch_0_dataInArray_1 : std_logic_vector(0 downto 0);
	signal branch_0_pValidArray_0 : std_logic;
	signal branch_0_pValidArray_1 : std_logic;
	signal branch_0_readyArray_0 : std_logic;
	signal branch_0_readyArray_1 : std_logic;
	signal branch_0_nReadyArray_0 : std_logic;
	signal branch_0_validArray_0 : std_logic;
	signal branch_0_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal branch_0_nReadyArray_1 : std_logic;
	signal branch_0_validArray_1 : std_logic;
	signal branch_0_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal branch_1_clk : std_logic;
	signal branch_1_rst : std_logic;
	signal branch_1_dataInArray_0 : std_logic_vector(31 downto 0);
	signal branch_1_dataInArray_1 : std_logic_vector(0 downto 0);
	signal branch_1_pValidArray_0 : std_logic;
	signal branch_1_pValidArray_1 : std_logic;
	signal branch_1_readyArray_0 : std_logic;
	signal branch_1_readyArray_1 : std_logic;
	signal branch_1_nReadyArray_0 : std_logic;
	signal branch_1_validArray_0 : std_logic;
	signal branch_1_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal branch_1_nReadyArray_1 : std_logic;
	signal branch_1_validArray_1 : std_logic;
	signal branch_1_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal branch_2_clk : std_logic;
	signal branch_2_rst : std_logic;
	signal branch_2_dataInArray_0 : std_logic_vector(31 downto 0);
	signal branch_2_dataInArray_1 : std_logic_vector(0 downto 0);
	signal branch_2_pValidArray_0 : std_logic;
	signal branch_2_pValidArray_1 : std_logic;
	signal branch_2_readyArray_0 : std_logic;
	signal branch_2_readyArray_1 : std_logic;
	signal branch_2_nReadyArray_0 : std_logic;
	signal branch_2_validArray_0 : std_logic;
	signal branch_2_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal branch_2_nReadyArray_1 : std_logic;
	signal branch_2_validArray_1 : std_logic;
	signal branch_2_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal fork_3_clk : std_logic;
	signal fork_3_rst : std_logic;
	signal fork_3_dataInArray_0 : std_logic_vector(31 downto 0);
	signal fork_3_pValidArray_0 : std_logic;
	signal fork_3_readyArray_0 : std_logic;
	signal fork_3_nReadyArray_0 : std_logic;
	signal fork_3_validArray_0 : std_logic;
	signal fork_3_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal fork_3_nReadyArray_1 : std_logic;
	signal fork_3_validArray_1 : std_logic;
	signal fork_3_dataOutArray_1 : std_logic_vector(31 downto 0);

	signal fork_4_clk : std_logic;
	signal fork_4_rst : std_logic;
	signal fork_4_dataInArray_0 : std_logic_vector(31 downto 0);
	signal fork_4_pValidArray_0 : std_logic;
	signal fork_4_readyArray_0 : std_logic;
	signal fork_4_nReadyArray_0 : std_logic;
	signal fork_4_validArray_0 : std_logic;
	signal fork_4_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal fork_4_nReadyArray_1 : std_logic;
	signal fork_4_validArray_1 : std_logic;
	signal fork_4_dataOutArray_1 : std_logic_vector(31 downto 0);
	signal fork_4_nReadyArray_2 : std_logic;
	signal fork_4_validArray_2 : std_logic;
	signal fork_4_dataOutArray_2 : std_logic_vector(31 downto 0);
	signal fork_4_nReadyArray_3 : std_logic;
	signal fork_4_validArray_3 : std_logic;
	signal fork_4_dataOutArray_3 : std_logic_vector(31 downto 0);
	signal fork_4_nReadyArray_4 : std_logic;
	signal fork_4_validArray_4 : std_logic;
	signal fork_4_dataOutArray_4 : std_logic_vector(31 downto 0);
	signal fork_4_nReadyArray_5 : std_logic;
	signal fork_4_validArray_5 : std_logic;
	signal fork_4_dataOutArray_5 : std_logic_vector(31 downto 0);

	signal ret_0_clk : std_logic;
	signal ret_0_rst : std_logic;
	signal ret_0_dataInArray_0 : std_logic_vector(31 downto 0);
	signal ret_0_pValidArray_0 : std_logic;
	signal ret_0_readyArray_0 : std_logic;
	signal ret_0_nReadyArray_0 : std_logic;
	signal ret_0_validArray_0 : std_logic;
	signal ret_0_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal MC_A_clk : std_logic;
	signal MC_A_rst : std_logic;
	signal MC_A_dataInArray_0 : std_logic_vector(31 downto 0);
	signal MC_A_dataInArray_1 : std_logic_vector(31 downto 0);
	signal MC_A_dataInArray_2 : std_logic_vector(31 downto 0);
	signal MC_A_dataInArray_3 : std_logic_vector(31 downto 0);
	signal MC_A_dataInArray_4 : std_logic_vector(31 downto 0);
	signal MC_A_pValidArray_0 : std_logic;
	signal MC_A_pValidArray_1 : std_logic;
	signal MC_A_pValidArray_2 : std_logic;
	signal MC_A_pValidArray_3 : std_logic;
	signal MC_A_pValidArray_4 : std_logic;
	signal MC_A_readyArray_0 : std_logic;
	signal MC_A_readyArray_1 : std_logic;
	signal MC_A_readyArray_2 : std_logic;
	signal MC_A_readyArray_3 : std_logic;
	signal MC_A_readyArray_4 : std_logic;
	signal MC_A_nReadyArray_0 : std_logic;
	signal MC_A_validArray_0 : std_logic;
	signal MC_A_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal MC_A_nReadyArray_1 : std_logic;
	signal MC_A_validArray_1 : std_logic;
	signal MC_A_dataOutArray_1 : std_logic_vector(31 downto 0);
	signal MC_A_nReadyArray_2 : std_logic;
	signal MC_A_validArray_2 : std_logic;
	signal MC_A_dataOutArray_2 : std_logic_vector(0 downto 0);
	signal MC_A_we0_ce0 : std_logic;

	signal sink_0_clk : std_logic;
	signal sink_0_rst : std_logic;
	signal sink_0_dataInArray_0 : std_logic_vector(31 downto 0);
	signal sink_0_pValidArray_0 : std_logic;
	signal sink_0_readyArray_0 : std_logic;

	signal sink_1_clk : std_logic;
	signal sink_1_rst : std_logic;
	signal sink_1_dataInArray_0 : std_logic_vector(31 downto 0);
	signal sink_1_pValidArray_0 : std_logic;
	signal sink_1_readyArray_0 : std_logic;

	signal end_0_clk : std_logic;
	signal end_0_rst : std_logic;
	signal end_0_dataInArray_0 : std_logic_vector(0 downto 0);
	signal end_0_dataInArray_1 : std_logic_vector(31 downto 0);
	signal end_0_pValidArray_0 : std_logic;
	signal end_0_pValidArray_1 : std_logic;
	signal end_0_readyArray_0 : std_logic;
	signal end_0_readyArray_1 : std_logic;
	signal end_0_nReadyArray_0 : std_logic;
	signal end_0_validArray_0 : std_logic;
	signal end_0_dataOutArray_0 : std_logic_vector(31 downto 0);
	signal end_0_validArray_1 :  std_logic;
	signal end_0_dataOutArray_1 :  std_logic_vector (31 downto 0);
	signal end_0_nReadyArray_1 :  std_logic;

	signal buffI_0_clk : std_logic;
	signal buffI_0_rst : std_logic;
	signal buffI_0_dataInArray_0 : std_logic_vector(31 downto 0);
	signal buffI_0_pValidArray_0 : std_logic;
	signal buffI_0_readyArray_0 : std_logic;
	signal buffI_0_nReadyArray_0 : std_logic;
	signal buffI_0_validArray_0 : std_logic;
	signal buffI_0_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal buffI_1_clk : std_logic;
	signal buffI_1_rst : std_logic;
	signal buffI_1_dataInArray_0 : std_logic_vector(31 downto 0);
	signal buffI_1_pValidArray_0 : std_logic;
	signal buffI_1_readyArray_0 : std_logic;
	signal buffI_1_nReadyArray_0 : std_logic;
	signal buffI_1_validArray_0 : std_logic;
	signal buffI_1_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal buffI_2_clk : std_logic;
	signal buffI_2_rst : std_logic;
	signal buffI_2_dataInArray_0 : std_logic_vector(31 downto 0);
	signal buffI_2_pValidArray_0 : std_logic;
	signal buffI_2_readyArray_0 : std_logic;
	signal buffI_2_nReadyArray_0 : std_logic;
	signal buffI_2_validArray_0 : std_logic;
	signal buffI_2_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal buffI_3_clk : std_logic;
	signal buffI_3_rst : std_logic;
	signal buffI_3_dataInArray_0 : std_logic_vector(31 downto 0);
	signal buffI_3_pValidArray_0 : std_logic;
	signal buffI_3_readyArray_0 : std_logic;
	signal buffI_3_nReadyArray_0 : std_logic;
	signal buffI_3_validArray_0 : std_logic;
	signal buffI_3_dataOutArray_0 : std_logic_vector(31 downto 0);

	signal buffI_4_clk : std_logic;
	signal buffI_4_rst : std_logic;
	signal buffI_4_dataInArray_0 : std_logic_vector(31 downto 0);
	signal buffI_4_pValidArray_0 : std_logic;
	signal buffI_4_readyArray_0 : std_logic;
	signal buffI_4_nReadyArray_0 : std_logic;
	signal buffI_4_validArray_0 : std_logic;
	signal buffI_4_dataOutArray_0 : std_logic_vector(31 downto 0);

begin


	arg_1_clk <= clk;
	arg_1_rst <= rst;
	arg_1_dataInArray_0 <= arg_1_din;
	arg_1_pValidArray_0 <= arg_1_valid_in;
	arg_1_ready_out <= arg_1_readyArray_0;
	Synch_0_pValidArray_0 <= arg_1_validArray_0;
	arg_1_nReadyArray_0 <= Synch_0_readyArray_0;
	Synch_0_dataInArray_0 <= std_logic_vector (resize(unsigned(arg_1_dataOutArray_0),Synch_0_dataInArray_0'length));

	cst_0_clk <= clk;
	cst_0_rst <= rst;
	Synch_0_pValidArray_1 <= cst_0_validArray_0;
	cst_0_nReadyArray_0 <= Synch_0_readyArray_1;
	Synch_0_dataInArray_1 <= std_logic_vector (resize(unsigned(cst_0_dataOutArray_0),Synch_0_dataInArray_1'length));

	cst_1_clk <= clk;
	cst_1_rst <= rst;
	Synch_0_pValidArray_2 <= cst_1_validArray_0;
	cst_1_nReadyArray_0 <= Synch_0_readyArray_2;
	Synch_0_dataInArray_2 <= std_logic_vector (resize(unsigned(cst_1_dataOutArray_0),Synch_0_dataInArray_2'length));

	start_0_clk <= clk;
	start_0_rst <= rst;
	start_0_pValidArray_0 <= start_valid;
	start_ready <= start_0_readyArray_0;
	forkC_5_pValidArray_0 <= start_0_validArray_0;
	start_0_nReadyArray_0 <= forkC_5_readyArray_0;
	forkC_5_dataInArray_0 <= std_logic_vector (resize(unsigned(start_0_dataOutArray_0),forkC_5_dataInArray_0'length));

	forkC_5_clk <= clk;
	forkC_5_rst <= rst;
	cst_0_pValidArray_0 <= forkC_5_validArray_0;
	forkC_5_nReadyArray_0 <= cst_0_readyArray_0;
	cst_0_dataInArray_0 <= "00000000000000000000000000000010";
	cst_1_pValidArray_0 <= forkC_5_validArray_1;
	forkC_5_nReadyArray_1 <= cst_1_readyArray_0;
	cst_1_dataInArray_0 <= "00000000000000000000000000000001";

	phi_0_clk <= clk;
	phi_0_rst <= rst;
	buffI_0_pValidArray_0 <= phi_0_validArray_0;
	phi_0_nReadyArray_0 <= buffI_0_readyArray_0;
	buffI_0_dataInArray_0 <= std_logic_vector (resize(unsigned(phi_0_dataOutArray_0),buffI_0_dataInArray_0'length));

	phi_1_clk <= clk;
	phi_1_rst <= rst;
	buffI_1_pValidArray_0 <= phi_1_validArray_0;
	phi_1_nReadyArray_0 <= buffI_1_readyArray_0;
	buffI_1_dataInArray_0 <= std_logic_vector (resize(unsigned(phi_1_dataOutArray_0),buffI_1_dataInArray_0'length));

	phi_2_clk <= clk;
	phi_2_rst <= rst;
	buffI_2_pValidArray_0 <= phi_2_validArray_0;
	phi_2_nReadyArray_0 <= buffI_2_readyArray_0;
	buffI_2_dataInArray_0 <= std_logic_vector (resize(unsigned(phi_2_dataOutArray_0),buffI_2_dataInArray_0'length));

	cst_2_clk <= clk;
	cst_2_rst <= rst;
	and_4_pValidArray_1 <= cst_2_validArray_0;
	cst_2_nReadyArray_0 <= and_4_readyArray_1;
	and_4_dataInArray_1 <= std_logic_vector (resize(unsigned(cst_2_dataOutArray_0),and_4_dataInArray_1'length));

	and_4_clk <= clk;
	and_4_rst <= rst;
	icmp_5_pValidArray_0 <= and_4_validArray_0;
	and_4_nReadyArray_0 <= icmp_5_readyArray_0;
	icmp_5_dataInArray_0 <= std_logic_vector (resize(unsigned(and_4_dataOutArray_0),icmp_5_dataInArray_0'length));

	cst_3_clk <= clk;
	cst_3_rst <= rst;
	icmp_5_pValidArray_1 <= cst_3_validArray_0;
	cst_3_nReadyArray_0 <= icmp_5_readyArray_1;
	icmp_5_dataInArray_1 <= std_logic_vector (resize(unsigned(cst_3_dataOutArray_0),icmp_5_dataInArray_1'length));

	icmp_5_clk <= clk;
	icmp_5_rst <= rst;
	fork_2_pValidArray_0 <= icmp_5_validArray_0;
	icmp_5_nReadyArray_0 <= fork_2_readyArray_0;
	fork_2_dataInArray_0 <= std_logic_vector (resize(unsigned(icmp_5_dataOutArray_0),fork_2_dataInArray_0'length));

	source_0_clk <= clk;
	source_0_rst <= rst;
	cst_2_pValidArray_0 <= source_0_validArray_0;
	source_0_nReadyArray_0 <= cst_2_readyArray_0;
	cst_2_dataInArray_0 <= "00000000000000000000000000000001";

	source_1_clk <= clk;
	source_1_rst <= rst;
	cst_3_pValidArray_0 <= source_1_validArray_0;
	source_1_nReadyArray_0 <= cst_3_readyArray_0;
	cst_3_dataInArray_0 <= "00000000000000000000000000000000";

	branch_3_clk <= clk;
	branch_3_rst <= rst;
	add_12_pValidArray_0 <= branch_3_validArray_0;
	branch_3_nReadyArray_0 <= add_12_readyArray_0;
	add_12_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_3_dataOutArray_0),add_12_dataInArray_0'length));
	load_9_pValidArray_1 <= branch_3_validArray_1;
	branch_3_nReadyArray_1 <= load_9_readyArray_1;
	load_9_dataInArray_1 <= std_logic_vector (resize(unsigned(branch_3_dataOutArray_1),load_9_dataInArray_1'length));

	branch_4_clk <= clk;
	branch_4_rst <= rst;
	add_16_pValidArray_0 <= branch_4_validArray_0;
	branch_4_nReadyArray_0 <= add_16_readyArray_0;
	add_16_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_4_dataOutArray_0),add_16_dataInArray_0'length));
	mul_10_pValidArray_0 <= branch_4_validArray_1;
	branch_4_nReadyArray_1 <= mul_10_readyArray_0;
	mul_10_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_4_dataOutArray_1),mul_10_dataInArray_0'length));

	branch_7_clk <= clk;
	branch_7_rst <= rst;
	phi_20_pValidArray_1 <= branch_7_validArray_0;
	branch_7_nReadyArray_0 <= phi_20_readyArray_1;
	phi_20_dataInArray_1 <= std_logic_vector (resize(unsigned(branch_7_dataOutArray_0),phi_20_dataInArray_1'length));
	add_17_pValidArray_0 <= branch_7_validArray_1;
	branch_7_nReadyArray_1 <= add_17_readyArray_0;
	add_17_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_7_dataOutArray_1),add_17_dataInArray_0'length));

	Synch_0_clk <= clk;
	Synch_0_rst <= rst;
	phi_0_pValidArray_1 <= Synch_0_validArray_0;
	Synch_0_nReadyArray_0 <= phi_0_readyArray_1;
	phi_0_dataInArray_1 <= std_logic_vector (resize(unsigned(Synch_0_dataOutArray_0),phi_0_dataInArray_1'length));
	phi_1_pValidArray_1 <= Synch_0_validArray_1;
	Synch_0_nReadyArray_1 <= phi_1_readyArray_1;
	phi_1_dataInArray_1 <= std_logic_vector (resize(unsigned(Synch_0_dataOutArray_1),phi_1_dataInArray_1'length));
	phi_2_pValidArray_1 <= Synch_0_validArray_2;
	Synch_0_nReadyArray_2 <= phi_2_readyArray_1;
	phi_2_dataInArray_1 <= std_logic_vector (resize(unsigned(Synch_0_dataOutArray_2),phi_2_dataInArray_1'length));

	fork_0_clk <= clk;
	fork_0_rst <= rst;
	and_4_pValidArray_0 <= fork_0_validArray_0;
	fork_0_nReadyArray_0 <= and_4_readyArray_0;
	and_4_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_0_dataOutArray_0),and_4_dataInArray_0'length));
	branch_7_pValidArray_0 <= fork_0_validArray_1;
	fork_0_nReadyArray_1 <= branch_7_readyArray_0;
	branch_7_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_0_dataOutArray_1),branch_7_dataInArray_0'length));

	fork_1_clk <= clk;
	fork_1_rst <= rst;
	add_21_pValidArray_0 <= fork_1_validArray_0;
	fork_1_nReadyArray_0 <= add_21_readyArray_0;
	add_21_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_1_dataOutArray_0),add_21_dataInArray_0'length));
	branch_3_pValidArray_0 <= fork_1_validArray_1;
	fork_1_nReadyArray_1 <= branch_3_readyArray_0;
	branch_3_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_1_dataOutArray_1),branch_3_dataInArray_0'length));

	fork_2_clk <= clk;
	fork_2_rst <= rst;
	branch_3_pValidArray_1 <= fork_2_validArray_0;
	fork_2_nReadyArray_0 <= branch_3_readyArray_1;
	branch_3_dataInArray_1 <= std_logic_vector (resize(unsigned(fork_2_dataOutArray_0),branch_3_dataInArray_1'length));
	branch_4_pValidArray_1 <= fork_2_validArray_1;
	fork_2_nReadyArray_1 <= branch_4_readyArray_1;
	branch_4_dataInArray_1 <= std_logic_vector (resize(unsigned(fork_2_dataOutArray_1),branch_4_dataInArray_1'length));
	branch_7_pValidArray_1 <= fork_2_validArray_2;
	fork_2_nReadyArray_2 <= branch_7_readyArray_1;
	branch_7_dataInArray_1 <= not std_logic_vector (resize(unsigned(fork_2_dataOutArray_2),branch_7_dataInArray_1'length));
	phi_19_pValidArray_0 <= fork_2_validArray_3;
	fork_2_nReadyArray_3 <= phi_19_readyArray_0;
	phi_19_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_2_dataOutArray_3),phi_19_dataInArray_0'length));
	phi_20_pValidArray_0 <= fork_2_validArray_4;
	fork_2_nReadyArray_4 <= phi_20_readyArray_0;
	phi_20_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_2_dataOutArray_4),phi_20_dataInArray_0'length));

	load_9_clk <= clk;
	load_9_rst <= rst;
	mul_10_pValidArray_1 <= load_9_validArray_0;
	load_9_nReadyArray_0 <= mul_10_readyArray_1;
	mul_10_dataInArray_1 <= std_logic_vector (resize(unsigned(load_9_dataOutArray_0),mul_10_dataInArray_1'length));
	MC_A_pValidArray_0 <= load_9_validArray_1;
	load_9_nReadyArray_1 <= MC_A_readyArray_0;
	MC_A_dataInArray_0 <= std_logic_vector (resize(unsigned(load_9_dataOutArray_1),MC_A_dataInArray_0'length));

	mul_10_clk <= clk;
	mul_10_rst <= rst;
	phi_19_pValidArray_1 <= mul_10_validArray_0;
	mul_10_nReadyArray_0 <= phi_19_readyArray_1;
	phi_19_dataInArray_1 <= std_logic_vector (resize(unsigned(mul_10_dataOutArray_0),phi_19_dataInArray_1'length));

	cst_4_clk <= clk;
	cst_4_rst <= rst;
	add_12_pValidArray_1 <= cst_4_validArray_0;
	cst_4_nReadyArray_0 <= add_12_readyArray_1;
	add_12_dataInArray_1 <= std_logic_vector (resize(unsigned(cst_4_dataOutArray_0),add_12_dataInArray_1'length));

	add_12_clk <= clk;
	add_12_rst <= rst;
	load_15_pValidArray_1 <= add_12_validArray_0;
	add_12_nReadyArray_0 <= load_15_readyArray_1;
	load_15_dataInArray_1 <= std_logic_vector (resize(unsigned(add_12_dataOutArray_0),load_15_dataInArray_1'length));

	load_15_clk <= clk;
	load_15_rst <= rst;
	add_16_pValidArray_1 <= load_15_validArray_0;
	load_15_nReadyArray_0 <= add_16_readyArray_1;
	add_16_dataInArray_1 <= std_logic_vector (resize(unsigned(load_15_dataOutArray_0),add_16_dataInArray_1'length));
	MC_A_pValidArray_1 <= load_15_validArray_1;
	load_15_nReadyArray_1 <= MC_A_readyArray_1;
	MC_A_dataInArray_1 <= std_logic_vector (resize(unsigned(load_15_dataOutArray_1),MC_A_dataInArray_1'length));

	add_16_clk <= clk;
	add_16_rst <= rst;
	phi_19_pValidArray_2 <= add_16_validArray_0;
	add_16_nReadyArray_0 <= phi_19_readyArray_2;
	phi_19_dataInArray_2 <= std_logic_vector (resize(unsigned(add_16_dataOutArray_0),phi_19_dataInArray_2'length));

	cst_5_clk <= clk;
	cst_5_rst <= rst;
	add_17_pValidArray_1 <= cst_5_validArray_0;
	cst_5_nReadyArray_0 <= add_17_readyArray_1;
	add_17_dataInArray_1 <= std_logic_vector (resize(unsigned(cst_5_dataOutArray_0),add_17_dataInArray_1'length));

	add_17_clk <= clk;
	add_17_rst <= rst;
	phi_20_pValidArray_2 <= add_17_validArray_0;
	add_17_nReadyArray_0 <= phi_20_readyArray_2;
	phi_20_dataInArray_2 <= std_logic_vector (resize(unsigned(add_17_dataOutArray_0),phi_20_dataInArray_2'length));

	source_2_clk <= clk;
	source_2_rst <= rst;
	cst_4_pValidArray_0 <= source_2_validArray_0;
	source_2_nReadyArray_0 <= cst_4_readyArray_0;
	cst_4_dataInArray_0 <= "11111111111111111111111111111111";

	source_3_clk <= clk;
	source_3_rst <= rst;
	cst_5_pValidArray_0 <= source_3_validArray_0;
	source_3_nReadyArray_0 <= cst_5_readyArray_0;
	cst_5_dataInArray_0 <= "00000000000000000000000000000001";

	phi_19_clk <= clk;
	phi_19_rst <= rst;
	buffI_3_pValidArray_0 <= phi_19_validArray_0;
	phi_19_nReadyArray_0 <= buffI_3_readyArray_0;
	buffI_3_dataInArray_0 <= std_logic_vector (resize(unsigned(phi_19_dataOutArray_0),buffI_3_dataInArray_0'length));

	phi_20_clk <= clk;
	phi_20_rst <= rst;
	buffI_4_pValidArray_0 <= phi_20_validArray_0;
	phi_20_nReadyArray_0 <= buffI_4_readyArray_0;
	buffI_4_dataInArray_0 <= std_logic_vector (resize(unsigned(phi_20_dataOutArray_0),buffI_4_dataInArray_0'length));

	cst_6_clk <= clk;
	cst_6_rst <= rst;
	add_21_pValidArray_1 <= cst_6_validArray_0;
	cst_6_nReadyArray_0 <= add_21_readyArray_1;
	add_21_dataInArray_1 <= std_logic_vector (resize(unsigned(cst_6_dataOutArray_0),add_21_dataInArray_1'length));

	add_21_clk <= clk;
	add_21_rst <= rst;
	fork_3_pValidArray_0 <= add_21_validArray_0;
	add_21_nReadyArray_0 <= fork_3_readyArray_0;
	fork_3_dataInArray_0 <= std_logic_vector (resize(unsigned(add_21_dataOutArray_0),fork_3_dataInArray_0'length));

	cst_7_clk <= clk;
	cst_7_rst <= rst;
	icmp_22_pValidArray_1 <= cst_7_validArray_0;
	cst_7_nReadyArray_0 <= icmp_22_readyArray_1;
	icmp_22_dataInArray_1 <= std_logic_vector (resize(unsigned(cst_7_dataOutArray_0),icmp_22_dataInArray_1'length));

	icmp_22_clk <= clk;
	icmp_22_rst <= rst;
	fork_4_pValidArray_0 <= icmp_22_validArray_0;
	icmp_22_nReadyArray_0 <= fork_4_readyArray_0;
	fork_4_dataInArray_0 <= std_logic_vector (resize(unsigned(icmp_22_dataOutArray_0),fork_4_dataInArray_0'length));

	source_4_clk <= clk;
	source_4_rst <= rst;
	cst_6_pValidArray_0 <= source_4_validArray_0;
	source_4_nReadyArray_0 <= cst_6_readyArray_0;
	cst_6_dataInArray_0 <= "00000000000000000000000000000001";

	source_5_clk <= clk;
	source_5_rst <= rst;
	cst_7_pValidArray_0 <= source_5_validArray_0;
	source_5_nReadyArray_0 <= cst_7_readyArray_0;
	cst_7_dataInArray_0 <= "00000000000000000000000000001010";

	branch_0_clk <= clk;
	branch_0_rst <= rst;
	sink_0_pValidArray_0 <= branch_0_validArray_0;
	branch_0_nReadyArray_0 <= sink_0_readyArray_0;
	sink_0_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_0_dataOutArray_0),sink_0_dataInArray_0'length));
	phi_0_pValidArray_2 <= branch_0_validArray_1;
	branch_0_nReadyArray_1 <= phi_0_readyArray_2;
	phi_0_dataInArray_2 <= std_logic_vector (resize(unsigned(branch_0_dataOutArray_1),phi_0_dataInArray_2'length));

	branch_1_clk <= clk;
	branch_1_rst <= rst;
	sink_1_pValidArray_0 <= branch_1_validArray_0;
	branch_1_nReadyArray_0 <= sink_1_readyArray_0;
	sink_1_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_1_dataOutArray_0),sink_1_dataInArray_0'length));
	phi_1_pValidArray_2 <= branch_1_validArray_1;
	branch_1_nReadyArray_1 <= phi_1_readyArray_2;
	phi_1_dataInArray_2 <= std_logic_vector (resize(unsigned(branch_1_dataOutArray_1),phi_1_dataInArray_2'length));

	branch_2_clk <= clk;
	branch_2_rst <= rst;
	ret_0_pValidArray_0 <= branch_2_validArray_0;
	branch_2_nReadyArray_0 <= ret_0_readyArray_0;
	ret_0_dataInArray_0 <= std_logic_vector (resize(unsigned(branch_2_dataOutArray_0),ret_0_dataInArray_0'length));
	phi_2_pValidArray_2 <= branch_2_validArray_1;
	branch_2_nReadyArray_1 <= phi_2_readyArray_2;
	phi_2_dataInArray_2 <= std_logic_vector (resize(unsigned(branch_2_dataOutArray_1),phi_2_dataInArray_2'length));

	fork_3_clk <= clk;
	fork_3_rst <= rst;
	icmp_22_pValidArray_0 <= fork_3_validArray_0;
	fork_3_nReadyArray_0 <= icmp_22_readyArray_0;
	icmp_22_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_3_dataOutArray_0),icmp_22_dataInArray_0'length));
	branch_1_pValidArray_0 <= fork_3_validArray_1;
	fork_3_nReadyArray_1 <= branch_1_readyArray_0;
	branch_1_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_3_dataOutArray_1),branch_1_dataInArray_0'length));

	fork_4_clk <= clk;
	fork_4_rst <= rst;
	branch_0_pValidArray_1 <= fork_4_validArray_0;
	fork_4_nReadyArray_0 <= branch_0_readyArray_1;
	branch_0_dataInArray_1 <= not std_logic_vector (resize(unsigned(fork_4_dataOutArray_0),branch_0_dataInArray_1'length));
	branch_1_pValidArray_1 <= fork_4_validArray_1;
	fork_4_nReadyArray_1 <= branch_1_readyArray_1;
	branch_1_dataInArray_1 <= not std_logic_vector (resize(unsigned(fork_4_dataOutArray_1),branch_1_dataInArray_1'length));
	branch_2_pValidArray_1 <= fork_4_validArray_2;
	fork_4_nReadyArray_2 <= branch_2_readyArray_1;
	branch_2_dataInArray_1 <= not std_logic_vector (resize(unsigned(fork_4_dataOutArray_2),branch_2_dataInArray_1'length));
	phi_0_pValidArray_0 <= fork_4_validArray_3;
	fork_4_nReadyArray_3 <= phi_0_readyArray_0;
	phi_0_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_4_dataOutArray_3),phi_0_dataInArray_0'length));
	phi_1_pValidArray_0 <= fork_4_validArray_4;
	fork_4_nReadyArray_4 <= phi_1_readyArray_0;
	phi_1_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_4_dataOutArray_4),phi_1_dataInArray_0'length));
	phi_2_pValidArray_0 <= fork_4_validArray_5;
	fork_4_nReadyArray_5 <= phi_2_readyArray_0;
	phi_2_dataInArray_0 <= std_logic_vector (resize(unsigned(fork_4_dataOutArray_5),phi_2_dataInArray_0'length));

	ret_0_clk <= clk;
	ret_0_rst <= rst;
	end_0_pValidArray_1 <= ret_0_validArray_0;
	ret_0_nReadyArray_0 <= end_0_readyArray_1;
	end_0_dataInArray_1 <= std_logic_vector (resize(unsigned(ret_0_dataOutArray_0),end_0_dataInArray_1'length));

	MC_A_clk <= clk;
	MC_A_rst <= rst;
	A_ce0 <= MC_A_we0_ce0;
	A_we0 <= MC_A_we0_ce0;
	load_9_pValidArray_0 <= MC_A_validArray_0;
	MC_A_nReadyArray_0 <= load_9_readyArray_0;
	load_9_dataInArray_0 <= std_logic_vector (resize(unsigned(MC_A_dataOutArray_0),load_9_dataInArray_0'length));
	load_15_pValidArray_0 <= MC_A_validArray_1;
	MC_A_nReadyArray_1 <= load_15_readyArray_0;
	load_15_dataInArray_0 <= std_logic_vector (resize(unsigned(MC_A_dataOutArray_1),load_15_dataInArray_0'length));
	end_0_pValidArray_0 <= MC_A_validArray_2;
	MC_A_nReadyArray_2 <= end_0_readyArray_0;
	end_0_dataInArray_0 <= std_logic_vector (resize(unsigned(MC_A_dataOutArray_2),end_0_dataInArray_0'length));

	sink_0_clk <= clk;
	sink_0_rst <= rst;

	sink_1_clk <= clk;
	sink_1_rst <= rst;

	end_0_clk <= clk;
	end_0_rst <= rst;
	end_valid <= end_0_validArray_0;
	end_out <= end_0_dataOutArray_0;
	end_0_nReadyArray_0 <= end_ready;

	buffI_0_clk <= clk;
	buffI_0_rst <= rst;
	fork_0_pValidArray_0 <= buffI_0_validArray_0;
	buffI_0_nReadyArray_0 <= fork_0_readyArray_0;
	fork_0_dataInArray_0 <= std_logic_vector (resize(unsigned(buffI_0_dataOutArray_0),fork_0_dataInArray_0'length));

	buffI_1_clk <= clk;
	buffI_1_rst <= rst;
	fork_1_pValidArray_0 <= buffI_1_validArray_0;
	buffI_1_nReadyArray_0 <= fork_1_readyArray_0;
	fork_1_dataInArray_0 <= std_logic_vector (resize(unsigned(buffI_1_dataOutArray_0),fork_1_dataInArray_0'length));

	buffI_2_clk <= clk;
	buffI_2_rst <= rst;
	branch_4_pValidArray_0 <= buffI_2_validArray_0;
	buffI_2_nReadyArray_0 <= branch_4_readyArray_0;
	branch_4_dataInArray_0 <= std_logic_vector (resize(unsigned(buffI_2_dataOutArray_0),branch_4_dataInArray_0'length));

	buffI_3_clk <= clk;
	buffI_3_rst <= rst;
	branch_2_pValidArray_0 <= buffI_3_validArray_0;
	buffI_3_nReadyArray_0 <= branch_2_readyArray_0;
	branch_2_dataInArray_0 <= std_logic_vector (resize(unsigned(buffI_3_dataOutArray_0),branch_2_dataInArray_0'length));

	buffI_4_clk <= clk;
	buffI_4_rst <= rst;
	branch_0_pValidArray_0 <= buffI_4_validArray_0;
	buffI_4_nReadyArray_0 <= branch_0_readyArray_0;
	branch_0_dataInArray_0 <= std_logic_vector (resize(unsigned(buffI_4_dataOutArray_0),branch_0_dataInArray_0'length));

arg_1: entity work.start_node(arch) generic map (1,1,32,32)
port map (
	clk => arg_1_clk,
	rst => arg_1_rst,
	dataInArray(0) => arg_1_dataInArray_0,
	pValidArray(0) => arg_1_pValidArray_0,
	readyArray(0) => arg_1_readyArray_0,
	nReadyArray(0) => arg_1_nReadyArray_0,
	validArray(0) => arg_1_validArray_0,
	dataOutArray(0) => arg_1_dataOutArray_0
);

cst_0: entity work.Const(arch) generic map (1,1,32,32)
port map (
	clk => cst_0_clk,
	rst => cst_0_rst,
	dataInArray(0) => cst_0_dataInArray_0,
	pValidArray(0) => cst_0_pValidArray_0,
	readyArray(0) => cst_0_readyArray_0,
	nReadyArray(0) => cst_0_nReadyArray_0,
	validArray(0) => cst_0_validArray_0,
	dataOutArray(0) => cst_0_dataOutArray_0
);

cst_1: entity work.Const(arch) generic map (1,1,32,32)
port map (
	clk => cst_1_clk,
	rst => cst_1_rst,
	dataInArray(0) => cst_1_dataInArray_0,
	pValidArray(0) => cst_1_pValidArray_0,
	readyArray(0) => cst_1_readyArray_0,
	nReadyArray(0) => cst_1_nReadyArray_0,
	validArray(0) => cst_1_validArray_0,
	dataOutArray(0) => cst_1_dataOutArray_0
);

start_0: entity work.start_node(arch) generic map (1,1,1,1)
port map (
	clk => start_0_clk,
	rst => start_0_rst,
	dataInArray(0) => start_0_dataInArray_0,
	pValidArray(0) => start_0_pValidArray_0,
	readyArray(0) => start_0_readyArray_0,
	nReadyArray(0) => start_0_nReadyArray_0,
	validArray(0) => start_0_validArray_0,
	dataOutArray(0) => start_0_dataOutArray_0
);

forkC_5: entity work.fork(arch) generic map (1,2,1,1)
port map (
	clk => forkC_5_clk,
	rst => forkC_5_rst,
	dataInArray(0) => forkC_5_dataInArray_0,
	pValidArray(0) => forkC_5_pValidArray_0,
	readyArray(0) => forkC_5_readyArray_0,
	nReadyArray(0) => forkC_5_nReadyArray_0,
	nReadyArray(1) => forkC_5_nReadyArray_1,
	validArray(0) => forkC_5_validArray_0,
	validArray(1) => forkC_5_validArray_1,
	dataOutArray(0) => forkC_5_dataOutArray_0,
	dataOutArray(1) => forkC_5_dataOutArray_1
);

phi_0: entity work.gian_mux_fifo(arch) generic map (3,1,32,32,1,3)
port map (
	clk => phi_0_clk,
	rst => phi_0_rst,
	Condition(0) => phi_0_dataInArray_0,
	dataInArray(0) => phi_0_dataInArray_1,
	dataInArray(1) => phi_0_dataInArray_2,
	pValidArray(0) => phi_0_pValidArray_0,
	pValidArray(1) => phi_0_pValidArray_1,
	pValidArray(2) => phi_0_pValidArray_2,
	readyArray(0) => phi_0_readyArray_0,
	readyArray(1) => phi_0_readyArray_1,
	readyArray(2) => phi_0_readyArray_2,
	nReadyArray(0) => phi_0_nReadyArray_0,
	validArray(0) => phi_0_validArray_0,
	dataOutArray(0) => phi_0_dataOutArray_0
);

phi_1: entity work.gian_mux_fifo(arch) generic map (3,1,32,32,1,3)
port map (
	clk => phi_1_clk,
	rst => phi_1_rst,
	Condition(0) => phi_1_dataInArray_0,
	dataInArray(0) => phi_1_dataInArray_1,
	dataInArray(1) => phi_1_dataInArray_2,
	pValidArray(0) => phi_1_pValidArray_0,
	pValidArray(1) => phi_1_pValidArray_1,
	pValidArray(2) => phi_1_pValidArray_2,
	readyArray(0) => phi_1_readyArray_0,
	readyArray(1) => phi_1_readyArray_1,
	readyArray(2) => phi_1_readyArray_2,
	nReadyArray(0) => phi_1_nReadyArray_0,
	validArray(0) => phi_1_validArray_0,
	dataOutArray(0) => phi_1_dataOutArray_0
);

phi_2: entity work.gian_mux_fifo(arch) generic map (3,1,32,32,1,3)
port map (
	clk => phi_2_clk,
	rst => phi_2_rst,
	Condition(0) => phi_2_dataInArray_0,
	dataInArray(0) => phi_2_dataInArray_1,
	dataInArray(1) => phi_2_dataInArray_2,
	pValidArray(0) => phi_2_pValidArray_0,
	pValidArray(1) => phi_2_pValidArray_1,
	pValidArray(2) => phi_2_pValidArray_2,
	readyArray(0) => phi_2_readyArray_0,
	readyArray(1) => phi_2_readyArray_1,
	readyArray(2) => phi_2_readyArray_2,
	nReadyArray(0) => phi_2_nReadyArray_0,
	validArray(0) => phi_2_validArray_0,
	dataOutArray(0) => phi_2_dataOutArray_0
);

cst_2: entity work.Const(arch) generic map (1,1,32,32)
port map (
	clk => cst_2_clk,
	rst => cst_2_rst,
	dataInArray(0) => cst_2_dataInArray_0,
	pValidArray(0) => cst_2_pValidArray_0,
	readyArray(0) => cst_2_readyArray_0,
	nReadyArray(0) => cst_2_nReadyArray_0,
	validArray(0) => cst_2_validArray_0,
	dataOutArray(0) => cst_2_dataOutArray_0
);

and_4: entity work.and_op(arch) generic map (2,1,32,32)
port map (
	clk => and_4_clk,
	rst => and_4_rst,
	dataInArray(0) => and_4_dataInArray_0,
	dataInArray(1) => and_4_dataInArray_1,
	pValidArray(0) => and_4_pValidArray_0,
	pValidArray(1) => and_4_pValidArray_1,
	readyArray(0) => and_4_readyArray_0,
	readyArray(1) => and_4_readyArray_1,
	nReadyArray(0) => and_4_nReadyArray_0,
	validArray(0) => and_4_validArray_0,
	dataOutArray(0) => and_4_dataOutArray_0
);

cst_3: entity work.Const(arch) generic map (1,1,32,32)
port map (
	clk => cst_3_clk,
	rst => cst_3_rst,
	dataInArray(0) => cst_3_dataInArray_0,
	pValidArray(0) => cst_3_pValidArray_0,
	readyArray(0) => cst_3_readyArray_0,
	nReadyArray(0) => cst_3_nReadyArray_0,
	validArray(0) => cst_3_validArray_0,
	dataOutArray(0) => cst_3_dataOutArray_0
);

icmp_5: entity work.icmp_eq_op(arch) generic map (2,1,32,1)
port map (
	clk => icmp_5_clk,
	rst => icmp_5_rst,
	dataInArray(0) => icmp_5_dataInArray_0,
	dataInArray(1) => icmp_5_dataInArray_1,
	pValidArray(0) => icmp_5_pValidArray_0,
	pValidArray(1) => icmp_5_pValidArray_1,
	readyArray(0) => icmp_5_readyArray_0,
	readyArray(1) => icmp_5_readyArray_1,
	nReadyArray(0) => icmp_5_nReadyArray_0,
	validArray(0) => icmp_5_validArray_0,
	dataOutArray(0) => icmp_5_dataOutArray_0
);

source_0: entity work.source(arch) generic map (0,1,32,1)
port map (
	clk => source_0_clk,
	rst => source_0_rst,
	nReadyArray(0) => source_0_nReadyArray_0,
	validArray(0) => source_0_validArray_0,
	dataOutArray(0) => source_0_dataOutArray_0
);

source_1: entity work.source(arch) generic map (0,1,32,1)
port map (
	clk => source_1_clk,
	rst => source_1_rst,
	nReadyArray(0) => source_1_nReadyArray_0,
	validArray(0) => source_1_validArray_0,
	dataOutArray(0) => source_1_dataOutArray_0
);

branch_3: entity work.Branch(arch) generic map (2,2,32,32)
port map (
	clk => branch_3_clk,
	rst => branch_3_rst,
	dataInArray(0) => branch_3_dataInArray_0,
	Condition(0) => branch_3_dataInArray_1,
	pValidArray(0) => branch_3_pValidArray_0,
	pValidArray(1) => branch_3_pValidArray_1,
	readyArray(0) => branch_3_readyArray_0,
	readyArray(1) => branch_3_readyArray_1,
	nReadyArray(0) => branch_3_nReadyArray_0,
	nReadyArray(1) => branch_3_nReadyArray_1,
	validArray(0) => branch_3_validArray_0,
	validArray(1) => branch_3_validArray_1,
	dataOutArray(0) => branch_3_dataOutArray_0,
	dataOutArray(1) => branch_3_dataOutArray_1
);

branch_4: entity work.Branch(arch) generic map (2,2,32,32)
port map (
	clk => branch_4_clk,
	rst => branch_4_rst,
	dataInArray(0) => branch_4_dataInArray_0,
	Condition(0) => branch_4_dataInArray_1,
	pValidArray(0) => branch_4_pValidArray_0,
	pValidArray(1) => branch_4_pValidArray_1,
	readyArray(0) => branch_4_readyArray_0,
	readyArray(1) => branch_4_readyArray_1,
	nReadyArray(0) => branch_4_nReadyArray_0,
	nReadyArray(1) => branch_4_nReadyArray_1,
	validArray(0) => branch_4_validArray_0,
	validArray(1) => branch_4_validArray_1,
	dataOutArray(0) => branch_4_dataOutArray_0,
	dataOutArray(1) => branch_4_dataOutArray_1
);

branch_7: entity work.Branch(arch) generic map (2,2,32,32)
port map (
	clk => branch_7_clk,
	rst => branch_7_rst,
	dataInArray(0) => branch_7_dataInArray_0,
	Condition(0) => branch_7_dataInArray_1,
	pValidArray(0) => branch_7_pValidArray_0,
	pValidArray(1) => branch_7_pValidArray_1,
	readyArray(0) => branch_7_readyArray_0,
	readyArray(1) => branch_7_readyArray_1,
	nReadyArray(0) => branch_7_nReadyArray_0,
	nReadyArray(1) => branch_7_nReadyArray_1,
	validArray(0) => branch_7_validArray_0,
	validArray(1) => branch_7_validArray_1,
	dataOutArray(0) => branch_7_dataOutArray_0,
	dataOutArray(1) => branch_7_dataOutArray_1
);

Synch_0: entity work.synch(arch) generic map (3,32,32)
port map (
	dataInArray(0) => Synch_0_dataInArray_0,
	dataInArray(1) => Synch_0_dataInArray_1,
	dataInArray(2) => Synch_0_dataInArray_2,
	pValidArray(0) => Synch_0_pValidArray_0,
	pValidArray(1) => Synch_0_pValidArray_1,
	pValidArray(2) => Synch_0_pValidArray_2,
	readyArray(0) => Synch_0_readyArray_0,
	readyArray(1) => Synch_0_readyArray_1,
	readyArray(2) => Synch_0_readyArray_2,
	nReadyArray(0) => Synch_0_nReadyArray_0,
	nReadyArray(1) => Synch_0_nReadyArray_1,
	nReadyArray(2) => Synch_0_nReadyArray_2,
	validArray(0) => Synch_0_validArray_0,
	validArray(1) => Synch_0_validArray_1,
	validArray(2) => Synch_0_validArray_2,
	dataOutArray(0) => Synch_0_dataOutArray_0,
	dataOutArray(1) => Synch_0_dataOutArray_1,
	dataOutArray(2) => Synch_0_dataOutArray_2
);

fork_0: entity work.fork(arch) generic map (1,2,32,32)
port map (
	clk => fork_0_clk,
	rst => fork_0_rst,
	dataInArray(0) => fork_0_dataInArray_0,
	pValidArray(0) => fork_0_pValidArray_0,
	readyArray(0) => fork_0_readyArray_0,
	nReadyArray(0) => fork_0_nReadyArray_0,
	nReadyArray(1) => fork_0_nReadyArray_1,
	validArray(0) => fork_0_validArray_0,
	validArray(1) => fork_0_validArray_1,
	dataOutArray(0) => fork_0_dataOutArray_0,
	dataOutArray(1) => fork_0_dataOutArray_1
);

fork_1: entity work.fork(arch) generic map (1,2,32,32)
port map (
	clk => fork_1_clk,
	rst => fork_1_rst,
	dataInArray(0) => fork_1_dataInArray_0,
	pValidArray(0) => fork_1_pValidArray_0,
	readyArray(0) => fork_1_readyArray_0,
	nReadyArray(0) => fork_1_nReadyArray_0,
	nReadyArray(1) => fork_1_nReadyArray_1,
	validArray(0) => fork_1_validArray_0,
	validArray(1) => fork_1_validArray_1,
	dataOutArray(0) => fork_1_dataOutArray_0,
	dataOutArray(1) => fork_1_dataOutArray_1
);

fork_2: entity work.fork(arch) generic map (1,5,32,32)
port map (
	clk => fork_2_clk,
	rst => fork_2_rst,
	dataInArray(0) => fork_2_dataInArray_0,
	pValidArray(0) => fork_2_pValidArray_0,
	readyArray(0) => fork_2_readyArray_0,
	nReadyArray(0) => fork_2_nReadyArray_0,
	nReadyArray(1) => fork_2_nReadyArray_1,
	nReadyArray(2) => fork_2_nReadyArray_2,
	nReadyArray(3) => fork_2_nReadyArray_3,
	nReadyArray(4) => fork_2_nReadyArray_4,
	validArray(0) => fork_2_validArray_0,
	validArray(1) => fork_2_validArray_1,
	validArray(2) => fork_2_validArray_2,
	validArray(3) => fork_2_validArray_3,
	validArray(4) => fork_2_validArray_4,
	dataOutArray(0) => fork_2_dataOutArray_0,
	dataOutArray(1) => fork_2_dataOutArray_1,
	dataOutArray(2) => fork_2_dataOutArray_2,
	dataOutArray(3) => fork_2_dataOutArray_3,
	dataOutArray(4) => fork_2_dataOutArray_4
);

load_9: entity work.mc_load_op(arch) generic map (2,2,32,32)
port map (
	clk => load_9_clk,
	rst => load_9_rst,
	dataInArray(0) => load_9_dataInArray_0,
	input_addr => load_9_dataInArray_1,
	pValidArray(0) => load_9_pValidArray_0,
	pValidArray(1) => load_9_pValidArray_1,
	readyArray(0) => load_9_readyArray_0,
	readyArray(1) => load_9_readyArray_1,
	nReadyArray(0) => load_9_nReadyArray_0,
	nReadyArray(1) => load_9_nReadyArray_1,
	validArray(0) => load_9_validArray_0,
	validArray(1) => load_9_validArray_1,
	dataOutArray(0) => load_9_dataOutArray_0,
	output_addr => load_9_dataOutArray_1
);

mul_10: entity work.mul_op(arch) generic map (2,1,32,32)
port map (
	clk => mul_10_clk,
	rst => mul_10_rst,
	dataInArray(0) => mul_10_dataInArray_0,
	dataInArray(1) => mul_10_dataInArray_1,
	pValidArray(0) => mul_10_pValidArray_0,
	pValidArray(1) => mul_10_pValidArray_1,
	readyArray(0) => mul_10_readyArray_0,
	readyArray(1) => mul_10_readyArray_1,
	nReadyArray(0) => mul_10_nReadyArray_0,
	validArray(0) => mul_10_validArray_0,
	dataOutArray(0) => mul_10_dataOutArray_0
);

cst_4: entity work.Const(arch) generic map (1,1,32,32)
port map (
	clk => cst_4_clk,
	rst => cst_4_rst,
	dataInArray(0) => cst_4_dataInArray_0,
	pValidArray(0) => cst_4_pValidArray_0,
	readyArray(0) => cst_4_readyArray_0,
	nReadyArray(0) => cst_4_nReadyArray_0,
	validArray(0) => cst_4_validArray_0,
	dataOutArray(0) => cst_4_dataOutArray_0
);

add_12: entity work.add_op(arch) generic map (2,1,32,32)
port map (
	clk => add_12_clk,
	rst => add_12_rst,
	dataInArray(0) => add_12_dataInArray_0,
	dataInArray(1) => add_12_dataInArray_1,
	pValidArray(0) => add_12_pValidArray_0,
	pValidArray(1) => add_12_pValidArray_1,
	readyArray(0) => add_12_readyArray_0,
	readyArray(1) => add_12_readyArray_1,
	nReadyArray(0) => add_12_nReadyArray_0,
	validArray(0) => add_12_validArray_0,
	dataOutArray(0) => add_12_dataOutArray_0
);

load_15: entity work.mc_load_op(arch) generic map (2,2,32,32)
port map (
	clk => load_15_clk,
	rst => load_15_rst,
	dataInArray(0) => load_15_dataInArray_0,
	input_addr => load_15_dataInArray_1,
	pValidArray(0) => load_15_pValidArray_0,
	pValidArray(1) => load_15_pValidArray_1,
	readyArray(0) => load_15_readyArray_0,
	readyArray(1) => load_15_readyArray_1,
	nReadyArray(0) => load_15_nReadyArray_0,
	nReadyArray(1) => load_15_nReadyArray_1,
	validArray(0) => load_15_validArray_0,
	validArray(1) => load_15_validArray_1,
	dataOutArray(0) => load_15_dataOutArray_0,
	output_addr => load_15_dataOutArray_1
);

add_16: entity work.add_op(arch) generic map (2,1,32,32)
port map (
	clk => add_16_clk,
	rst => add_16_rst,
	dataInArray(0) => add_16_dataInArray_0,
	dataInArray(1) => add_16_dataInArray_1,
	pValidArray(0) => add_16_pValidArray_0,
	pValidArray(1) => add_16_pValidArray_1,
	readyArray(0) => add_16_readyArray_0,
	readyArray(1) => add_16_readyArray_1,
	nReadyArray(0) => add_16_nReadyArray_0,
	validArray(0) => add_16_validArray_0,
	dataOutArray(0) => add_16_dataOutArray_0
);

cst_5: entity work.Const(arch) generic map (1,1,32,32)
port map (
	clk => cst_5_clk,
	rst => cst_5_rst,
	dataInArray(0) => cst_5_dataInArray_0,
	pValidArray(0) => cst_5_pValidArray_0,
	readyArray(0) => cst_5_readyArray_0,
	nReadyArray(0) => cst_5_nReadyArray_0,
	validArray(0) => cst_5_validArray_0,
	dataOutArray(0) => cst_5_dataOutArray_0
);

add_17: entity work.add_op(arch) generic map (2,1,32,32)
port map (
	clk => add_17_clk,
	rst => add_17_rst,
	dataInArray(0) => add_17_dataInArray_0,
	dataInArray(1) => add_17_dataInArray_1,
	pValidArray(0) => add_17_pValidArray_0,
	pValidArray(1) => add_17_pValidArray_1,
	readyArray(0) => add_17_readyArray_0,
	readyArray(1) => add_17_readyArray_1,
	nReadyArray(0) => add_17_nReadyArray_0,
	validArray(0) => add_17_validArray_0,
	dataOutArray(0) => add_17_dataOutArray_0
);

source_2: entity work.source(arch) generic map (0,1,32,1)
port map (
	clk => source_2_clk,
	rst => source_2_rst,
	nReadyArray(0) => source_2_nReadyArray_0,
	validArray(0) => source_2_validArray_0,
	dataOutArray(0) => source_2_dataOutArray_0
);

source_3: entity work.source(arch) generic map (0,1,32,1)
port map (
	clk => source_3_clk,
	rst => source_3_rst,
	nReadyArray(0) => source_3_nReadyArray_0,
	validArray(0) => source_3_validArray_0,
	dataOutArray(0) => source_3_dataOutArray_0
);

phi_19: entity work.Mux(arch) generic map (3,1,32,32,1)
port map (
	clk => phi_19_clk,
	rst => phi_19_rst,
	Condition(0) => phi_19_dataInArray_0,
	dataInArray(0) => phi_19_dataInArray_1,
	dataInArray(1) => phi_19_dataInArray_2,
	pValidArray(0) => phi_19_pValidArray_0,
	pValidArray(1) => phi_19_pValidArray_1,
	pValidArray(2) => phi_19_pValidArray_2,
	readyArray(0) => phi_19_readyArray_0,
	readyArray(1) => phi_19_readyArray_1,
	readyArray(2) => phi_19_readyArray_2,
	nReadyArray(0) => phi_19_nReadyArray_0,
	validArray(0) => phi_19_validArray_0,
	dataOutArray(0) => phi_19_dataOutArray_0
);

phi_20: entity work.Mux(arch) generic map (3,1,32,32,1)
port map (
	clk => phi_20_clk,
	rst => phi_20_rst,
	Condition(0) => phi_20_dataInArray_0,
	dataInArray(0) => phi_20_dataInArray_1,
	dataInArray(1) => phi_20_dataInArray_2,
	pValidArray(0) => phi_20_pValidArray_0,
	pValidArray(1) => phi_20_pValidArray_1,
	pValidArray(2) => phi_20_pValidArray_2,
	readyArray(0) => phi_20_readyArray_0,
	readyArray(1) => phi_20_readyArray_1,
	readyArray(2) => phi_20_readyArray_2,
	nReadyArray(0) => phi_20_nReadyArray_0,
	validArray(0) => phi_20_validArray_0,
	dataOutArray(0) => phi_20_dataOutArray_0
);

cst_6: entity work.Const(arch) generic map (1,1,32,32)
port map (
	clk => cst_6_clk,
	rst => cst_6_rst,
	dataInArray(0) => cst_6_dataInArray_0,
	pValidArray(0) => cst_6_pValidArray_0,
	readyArray(0) => cst_6_readyArray_0,
	nReadyArray(0) => cst_6_nReadyArray_0,
	validArray(0) => cst_6_validArray_0,
	dataOutArray(0) => cst_6_dataOutArray_0
);

add_21: entity work.add_op(arch) generic map (2,1,32,32)
port map (
	clk => add_21_clk,
	rst => add_21_rst,
	dataInArray(0) => add_21_dataInArray_0,
	dataInArray(1) => add_21_dataInArray_1,
	pValidArray(0) => add_21_pValidArray_0,
	pValidArray(1) => add_21_pValidArray_1,
	readyArray(0) => add_21_readyArray_0,
	readyArray(1) => add_21_readyArray_1,
	nReadyArray(0) => add_21_nReadyArray_0,
	validArray(0) => add_21_validArray_0,
	dataOutArray(0) => add_21_dataOutArray_0
);

cst_7: entity work.Const(arch) generic map (1,1,32,32)
port map (
	clk => cst_7_clk,
	rst => cst_7_rst,
	dataInArray(0) => cst_7_dataInArray_0,
	pValidArray(0) => cst_7_pValidArray_0,
	readyArray(0) => cst_7_readyArray_0,
	nReadyArray(0) => cst_7_nReadyArray_0,
	validArray(0) => cst_7_validArray_0,
	dataOutArray(0) => cst_7_dataOutArray_0
);

icmp_22: entity work.icmp_ult_op(arch) generic map (2,1,32,1)
port map (
	clk => icmp_22_clk,
	rst => icmp_22_rst,
	dataInArray(0) => icmp_22_dataInArray_0,
	dataInArray(1) => icmp_22_dataInArray_1,
	pValidArray(0) => icmp_22_pValidArray_0,
	pValidArray(1) => icmp_22_pValidArray_1,
	readyArray(0) => icmp_22_readyArray_0,
	readyArray(1) => icmp_22_readyArray_1,
	nReadyArray(0) => icmp_22_nReadyArray_0,
	validArray(0) => icmp_22_validArray_0,
	dataOutArray(0) => icmp_22_dataOutArray_0
);

source_4: entity work.source(arch) generic map (0,1,32,1)
port map (
	clk => source_4_clk,
	rst => source_4_rst,
	nReadyArray(0) => source_4_nReadyArray_0,
	validArray(0) => source_4_validArray_0,
	dataOutArray(0) => source_4_dataOutArray_0
);

source_5: entity work.source(arch) generic map (0,1,32,1)
port map (
	clk => source_5_clk,
	rst => source_5_rst,
	nReadyArray(0) => source_5_nReadyArray_0,
	validArray(0) => source_5_validArray_0,
	dataOutArray(0) => source_5_dataOutArray_0
);

branch_0: entity work.Branch(arch) generic map (2,2,32,32)
port map (
	clk => branch_0_clk,
	rst => branch_0_rst,
	dataInArray(0) => branch_0_dataInArray_0,
	Condition(0) => branch_0_dataInArray_1,
	pValidArray(0) => branch_0_pValidArray_0,
	pValidArray(1) => branch_0_pValidArray_1,
	readyArray(0) => branch_0_readyArray_0,
	readyArray(1) => branch_0_readyArray_1,
	nReadyArray(0) => branch_0_nReadyArray_0,
	nReadyArray(1) => branch_0_nReadyArray_1,
	validArray(0) => branch_0_validArray_0,
	validArray(1) => branch_0_validArray_1,
	dataOutArray(0) => branch_0_dataOutArray_0,
	dataOutArray(1) => branch_0_dataOutArray_1
);

branch_1: entity work.Branch(arch) generic map (2,2,32,32)
port map (
	clk => branch_1_clk,
	rst => branch_1_rst,
	dataInArray(0) => branch_1_dataInArray_0,
	Condition(0) => branch_1_dataInArray_1,
	pValidArray(0) => branch_1_pValidArray_0,
	pValidArray(1) => branch_1_pValidArray_1,
	readyArray(0) => branch_1_readyArray_0,
	readyArray(1) => branch_1_readyArray_1,
	nReadyArray(0) => branch_1_nReadyArray_0,
	nReadyArray(1) => branch_1_nReadyArray_1,
	validArray(0) => branch_1_validArray_0,
	validArray(1) => branch_1_validArray_1,
	dataOutArray(0) => branch_1_dataOutArray_0,
	dataOutArray(1) => branch_1_dataOutArray_1
);

branch_2: entity work.Branch(arch) generic map (2,2,32,32)
port map (
	clk => branch_2_clk,
	rst => branch_2_rst,
	dataInArray(0) => branch_2_dataInArray_0,
	Condition(0) => branch_2_dataInArray_1,
	pValidArray(0) => branch_2_pValidArray_0,
	pValidArray(1) => branch_2_pValidArray_1,
	readyArray(0) => branch_2_readyArray_0,
	readyArray(1) => branch_2_readyArray_1,
	nReadyArray(0) => branch_2_nReadyArray_0,
	nReadyArray(1) => branch_2_nReadyArray_1,
	validArray(0) => branch_2_validArray_0,
	validArray(1) => branch_2_validArray_1,
	dataOutArray(0) => branch_2_dataOutArray_0,
	dataOutArray(1) => branch_2_dataOutArray_1
);

fork_3: entity work.fork(arch) generic map (1,2,32,32)
port map (
	clk => fork_3_clk,
	rst => fork_3_rst,
	dataInArray(0) => fork_3_dataInArray_0,
	pValidArray(0) => fork_3_pValidArray_0,
	readyArray(0) => fork_3_readyArray_0,
	nReadyArray(0) => fork_3_nReadyArray_0,
	nReadyArray(1) => fork_3_nReadyArray_1,
	validArray(0) => fork_3_validArray_0,
	validArray(1) => fork_3_validArray_1,
	dataOutArray(0) => fork_3_dataOutArray_0,
	dataOutArray(1) => fork_3_dataOutArray_1
);

fork_4: entity work.fork(arch) generic map (1,6,32,32)
port map (
	clk => fork_4_clk,
	rst => fork_4_rst,
	dataInArray(0) => fork_4_dataInArray_0,
	pValidArray(0) => fork_4_pValidArray_0,
	readyArray(0) => fork_4_readyArray_0,
	nReadyArray(0) => fork_4_nReadyArray_0,
	nReadyArray(1) => fork_4_nReadyArray_1,
	nReadyArray(2) => fork_4_nReadyArray_2,
	nReadyArray(3) => fork_4_nReadyArray_3,
	nReadyArray(4) => fork_4_nReadyArray_4,
	nReadyArray(5) => fork_4_nReadyArray_5,
	validArray(0) => fork_4_validArray_0,
	validArray(1) => fork_4_validArray_1,
	validArray(2) => fork_4_validArray_2,
	validArray(3) => fork_4_validArray_3,
	validArray(4) => fork_4_validArray_4,
	validArray(5) => fork_4_validArray_5,
	dataOutArray(0) => fork_4_dataOutArray_0,
	dataOutArray(1) => fork_4_dataOutArray_1,
	dataOutArray(2) => fork_4_dataOutArray_2,
	dataOutArray(3) => fork_4_dataOutArray_3,
	dataOutArray(4) => fork_4_dataOutArray_4,
	dataOutArray(5) => fork_4_dataOutArray_5
);

ret_0: entity work.ret_op(arch) generic map (1,1,32,32)
port map (
	clk => ret_0_clk,
	rst => ret_0_rst,
	dataInArray(0) => ret_0_dataInArray_0,
	pValidArray(0) => ret_0_pValidArray_0,
	readyArray(0) => ret_0_readyArray_0,
	nReadyArray(0) => ret_0_nReadyArray_0,
	validArray(0) => ret_0_validArray_0,
	dataOutArray(0) => ret_0_dataOutArray_0
);

MC_A: entity work.MemCont(arch) generic map (32,32,1,2,1)
port map (
	clk => MC_A_clk,
	rst => MC_A_rst,
	io_storeDataOut => A_dout0,
	io_storeAddrOut => A_address0,
	io_storeEnable => MC_A_we0_ce0,
	io_loadDataIn => A_din1,
	io_loadAddrOut => A_address1,
	io_loadEnable => A_ce1,
	io_bbReadyToPrevs(0) => MC_A_readyArray_2,
	io_bbpValids(0) => '0',
	io_bb_stCountArray(0) => x"00000000",
	io_rdPortsPrev_ready(0) => MC_A_readyArray_0,
	io_rdPortsPrev_ready(1) => MC_A_readyArray_1,
	io_rdPortsPrev_valid(0) => MC_A_pValidArray_0,
	io_rdPortsPrev_valid(1) => MC_A_pValidArray_1,
	io_rdPortsPrev_bits(0) => MC_A_dataInArray_0,
	io_rdPortsPrev_bits(1) => MC_A_dataInArray_1,
	io_wrAddrPorts_ready(0) => MC_A_readyArray_3,
	io_wrAddrPorts_valid(0) => MC_A_pValidArray_3,
	io_wrAddrPorts_bits(0) => MC_A_dataInArray_3,
	io_wrDataPorts_ready(0) => MC_A_readyArray_4,
	io_wrDataPorts_valid(0) => MC_A_pValidArray_4,
	io_wrDataPorts_bits(0) => MC_A_dataInArray_4,
	io_rdPortsNext_ready(0) => MC_A_nReadyArray_0,
	io_rdPortsNext_ready(1) => MC_A_nReadyArray_1,
	io_rdPortsNext_valid(0) => MC_A_validArray_0,
	io_rdPortsNext_valid(1) => MC_A_validArray_1,
	io_rdPortsNext_bits(0) => MC_A_dataOutArray_0,
	io_rdPortsNext_bits(1) => MC_A_dataOutArray_1,
	io_Empty_Valid => MC_A_validArray_2,
	io_Empty_Ready => MC_A_nReadyArray_2

);

sink_0: entity work.sink(arch) generic map (1,0,32,32)
port map (
	clk => sink_0_clk,
	rst => sink_0_rst,
	dataInArray(0) => sink_0_dataInArray_0,
	pValidArray(0) => sink_0_pValidArray_0,
	readyArray(0) => sink_0_readyArray_0
);

sink_1: entity work.sink(arch) generic map (1,0,32,32)
port map (
	clk => sink_1_clk,
	rst => sink_1_rst,
	dataInArray(0) => sink_1_dataInArray_0,
	pValidArray(0) => sink_1_pValidArray_0,
	readyArray(0) => sink_1_readyArray_0
);

end_0: entity work.end_node(arch) generic map (1,1,1,32,32)
port map (
	clk => end_0_clk,
	rst => end_0_rst,
	dataInArray(0) => end_0_dataInArray_1,
	eValidArray(0) => end_0_pValidArray_0,
	pValidArray(0) => end_0_pValidArray_1,
	eReadyArray(0) => end_0_readyArray_0,
	readyArray(0) => end_0_readyArray_1,
	dataOutArray(0) => end_0_dataOutArray_0,
	validArray(0) => end_0_validArray_0,
	nReadyArray(0) => end_0_nReadyArray_0
);

buffI_0: entity work.elasticBuffer(arch) generic map (1,1,32,32)
port map (
	clk => buffI_0_clk,
	rst => buffI_0_rst,
	dataInArray(0) => buffI_0_dataInArray_0,
	pValidArray(0) => buffI_0_pValidArray_0,
	readyArray(0) => buffI_0_readyArray_0,
	nReadyArray(0) => buffI_0_nReadyArray_0,
	validArray(0) => buffI_0_validArray_0,
	dataOutArray(0) => buffI_0_dataOutArray_0
);

buffI_1: entity work.elasticBuffer(arch) generic map (1,1,32,32)
port map (
	clk => buffI_1_clk,
	rst => buffI_1_rst,
	dataInArray(0) => buffI_1_dataInArray_0,
	pValidArray(0) => buffI_1_pValidArray_0,
	readyArray(0) => buffI_1_readyArray_0,
	nReadyArray(0) => buffI_1_nReadyArray_0,
	validArray(0) => buffI_1_validArray_0,
	dataOutArray(0) => buffI_1_dataOutArray_0
);

buffI_2: entity work.elasticBuffer(arch) generic map (1,1,32,32)
port map (
	clk => buffI_2_clk,
	rst => buffI_2_rst,
	dataInArray(0) => buffI_2_dataInArray_0,
	pValidArray(0) => buffI_2_pValidArray_0,
	readyArray(0) => buffI_2_readyArray_0,
	nReadyArray(0) => buffI_2_nReadyArray_0,
	validArray(0) => buffI_2_validArray_0,
	dataOutArray(0) => buffI_2_dataOutArray_0
);

buffI_3: entity work.elasticBuffer(arch) generic map (1,1,32,32)
port map (
	clk => buffI_3_clk,
	rst => buffI_3_rst,
	dataInArray(0) => buffI_3_dataInArray_0,
	pValidArray(0) => buffI_3_pValidArray_0,
	readyArray(0) => buffI_3_readyArray_0,
	nReadyArray(0) => buffI_3_nReadyArray_0,
	validArray(0) => buffI_3_validArray_0,
	dataOutArray(0) => buffI_3_dataOutArray_0
);

buffI_4: entity work.elasticBuffer(arch) generic map (1,1,32,32)
port map (
	clk => buffI_4_clk,
	rst => buffI_4_rst,
	dataInArray(0) => buffI_4_dataInArray_0,
	pValidArray(0) => buffI_4_pValidArray_0,
	readyArray(0) => buffI_4_readyArray_0,
	nReadyArray(0) => buffI_4_nReadyArray_0,
	validArray(0) => buffI_4_validArray_0,
	dataOutArray(0) => buffI_4_dataOutArray_0
);

end behavioral; 
